# 1.RPODUCT, OFFLINE_SALE테이블에서 상품코드 별 매출액(판매가*판매량)합계 출력
# 2. 결과는 매출액을 기준으로 내림차순, 매출액 같다면 상품코드 기준 오름차순 

SELECT B.PRODUCT_CODE, SUM(B.PRICE * A.SALES_AMOUNT) AS SALES
FROM PRODUCT B
JOIN OFFLINE_SALE A ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY B.PRODUCT_CODE
ORDER BY SALES DESC, B.PRODUCT_CODE