# 1. RPODUCT 테이블과 OFFLINE_SALE 테이블에서 상품코드 별 매출액(판매가*판매량) 합계를 출력하는 SQL문 작성
# 2. 결과는 매출액을 기준으로 내림차순 정렬
# 3. 매출액이 같다면 상품코드를 기준으로 오름차순 정렬

SELECT B.PRODUCT_CODE, SUM(B.PRICE * A.SALES_AMOUNT) AS SALES
FROM PRODUCT B
JOIN OFFLINE_SALE A ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY B.PRODUCT_CODE
ORDER BY SALES DESC, B.PRODUCT_CODE