# 1. '경제' 카테고리에 속하는 도서들의 BOOK_ID, AUTHOR_NAME, PUBLISHED_DATE 리스트를 출력하는 SQL
# 2. PUBLISHED_DATE를 기준으로 오름차순

SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK B
JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE B.CATEGORY = '경제'
ORDER BY B.PUBLISHED_DATE